### ISSUE TITLE
Can't change require line?

### ISSUE THREAD

**Issue by jkr2255** [riot/webpack-loader#16]
In current version of `riot-tag-loader`, `var riot = require('riot')` is hard-coded ([line](https://github.com/riot/tag-loader/blob/670af11a7a85abd0a56a03ba28ef10e23ba28a63/index.js#L59)).

If we want Riot tags to treat as ES6 Modules, require line should be `import riot from 'riot'`. 

The line shoud be configured, at least the selection of `require`/`import`.

**Comment by GianlucaGuarini** [comment]
this issue was solved in the new v4.0.0 version
