### ISSUE TITLE
Hot reload not working on Windows

### ISSUE THREAD

**Issue by luffs** [riot/webpack-loader#27]
There's a problem with the path variable in the hotReload(path) function, since Windows uses the backslash character as folder separator. 

> ERROR in ./src/tags/test.riot
Module not found: Error: Can't resolve 'C:UsersLuffDesktolehsrc agstest.riot' in 'C:\Users\Luff\Desktop\bleh\src\tags'
 @ ./src/tags/test.riot 23:24-80
 @ ./src/index.js
i ｢wdm｣: Failed to compile.

I've made a pull request https://github.com/riot/webpack-loader/pull/26 .

**Comment by GianlucaGuarini** [comment]
Fixed with https://github.com/riot/webpack-loader/pull/29
