### ISSUE TITLE
missing sass & es6 support

### ISSUE THREAD

**Issue by SassNinja** [riot/webpack-loader#28]
With riot v3 I really enjoyed the handy options `style: 'scss'` and `type: 'es6'`.
But seems they are not implemented anymore in riot v4 and I need to register my own preprocessor and postprocessor. So I've done the following in my `webpack.config.js`

```javascript
const compiler = require('@riotjs/compiler');
const sass = require('node-sass');

compiler.registerPreprocessor('css', 'sass', function(code, { options }) {
    const { file } = options;
  
    console.log('Compile the sass code in', file);
  
    const css = sass.renderSync({
        data: code
    });
  
    return {
        code: css,
        map: null
    };
});

module.exports = {
    ...
    module: {
        rules: [
            {
                test: /\.riot$/,
                use: [
                    {
                        loader: '@riotjs/webpack-loader',
                        options: {
                            css: 'sass',
                        }
                    }
                ]
            }
        ]
    }
};
```

Unfortunately this hasn't worked: the emitted file still contained scss code and I didn't see any console.log

**Comment by SassNinja** [comment]
Maybe worth to mention that the preprocessor gets at least executed (in contrary to the preprocessor) but using `buble` (as described in the docs) doesn't work for me:
I get the error
```
ERROR in ./src/components/my-list.riot
Module build failed (from ./node_modules/@riotjs/webpack-loader/dist/riot-webpack-loader.cjs.js):
Error
    at Function.missingTransform
...
```

However using babel seems to works without any problem.
```javascript
compiler.registerPostprocessor(function(code, { options }) {
    return babel.transform(code, {
        sourceMaps: false,
        presets: [[
            '@babel/env',
            {
                modules: false
            }
        ]]
    });
});
```

So major issue I'm facing right now is the missing scss compilation.

**Comment by GianlucaGuarini** [comment]
Are you using `<style type="sass">`? In your components?

**Comment by SassNinja** [comment]
ah ok, that was the reason why the preprocessor wasn't executed (I expected the same behavior as in riot v3 meaning no need to add `type="sass"` in every component).

However I now get a compilation error:
```
ERROR in ./src/components/my-list.riot
Module build failed (from ./node_modules/@riotjs/webpack-loader/dist/riot-webpack-loader.cjs.js):
TypeError: css.replace is not a function
    at scopedCSS
...
```

**Comment by GianlucaGuarini** [comment]
`type="sass"` is now mandatory in order your IDE can recognize what kind of syntax you are using for your styles. Could you please dump your tag content and I will be able to test it by myself? thank you

**Comment by GianlucaGuarini** [comment]
Ok the issue is in your preprocessor. Sass doesn't return a string as output but an object where the `css` is a `Buffer`.

I have fixed your code and prepared a demo for you https://runkit.com/gianlucaguarini/riot-compiler-scss-test

**Comment by SassNinja** [comment]
Thanks for the help!

I think the official docs should be adjusted then because I used the code snippet from it
https://riot.js.org/compiler/#pre-processors

**Comment by GianlucaGuarini** [comment]
@SassNinja a PR on that part of the documentation is appreciated. Otherwise I will fix it asap
