### ISSUE TITLE
Example link leads to 404

### ISSUE THREAD

**Issue by johntringham** [riot/webpack-loader#45]
Hi,

At the bottom of the readme.md there's a link that says:

> Please check [this simple example](https://github.com/riot/examples/tree/gh-pages/webpack) to see how it's easy to configure webpack with riot

This link leads to here: https://github.com/riot/examples/tree/gh-pages/webpack - which currently is dead

Any chance the example could be reinstated, or the link changed to be pointing to the right place?

Thanks

edit: Looks like the problem is that this example doesn't exist (anymore?) on the gh-pages branch, which is where the link is pointing. Changing the link to https://github.com/riot/examples/tree/next/webpack looks like the right thing to do

**Comment by johntringham** [comment]
Looks like this example was deleted in 2022 without explanation or replacement

https://github.com/riot/examples/commit/85a37563a56f10bf578c84bf19741f5428b7b1db

Is there a reason why? Does riot still support webpack?

**Comment by GianlucaGuarini** [comment]
Thank you for this issue. I have updated the readme adding the missing webpack examples.
The examples repo contains already 3 webpack projects and It makes no sense to keep alive a 4th one just to show how a webpack config should look like. 

Consider also that `npm init riot` creates a template with a default webpack configuration, my intent is to avoid redundant stuff across the Riot.js repos.
